# Production Docker Compose Configuration
# Usage: docker compose -f docker-compose.prod.yml up -d
# Features: Optimized builds, no volume mounts, production-ready

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: prod-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app
      - DATABASE_URL=postgres://csuser:change_me@postgres:5432/cslibrary
    env_file:
      - ./backend/.env.prod
    volumes:
      # Only persist uploads, no source code mounts
      - backend_uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: prod-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://csuser:change_me@postgres:5432/cslibrary
    depends_on:
      - backend
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: csuser
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: cslibrary
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U csuser -d cslibrary"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  backend_uploads:
  db_data:
