# Production Docker Compose Configuration
# Usage: docker compose -f docker-compose.prod.yml up -d
# Features: Optimized builds, no volume mounts, production-ready

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: prod-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env.prod
    volumes:
      # Only persist uploads, no source code mounts
      - backend_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: prod-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_uploads:
