[build]
  publish = "frontend/dist"
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-name.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://your-backend-name.onrender.com/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://your-backend-name.onrender.com"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://your-backend-name.onrender.com"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://your-backend-name.onrender.com"
