services:
  # PostgreSQL 数据库服务
  postgresql:
    image: postgres:17.6-alpine
    container_name: postgresql
    env_file:
      - .env.deploy
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - cslibrary-net

  # 后端服务
  cslibrary-backend:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.backend
    container_name: cslibrary-backend
    ports:
      - "8000:8000"
    env_file:
      - .env.deploy
    environment:
      - APP_WORKERS=${APP_WORKERS:-2}
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - backend_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/api/health || curl -fsS http://localhost:8000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - cslibrary-net

  # 前端服务
  cslibrary-frontend:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.frontend
      args:
        VITE_API_BASE_URL: http://cslibrary-backend:8000
    container_name: cslibrary-frontend
    ports:
      - "80:80"
    depends_on:
      - cslibrary-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1/ > /dev/null"]
      interval: 15s
      timeout: 3s
      retries: 5
    networks:
      - cslibrary-net

volumes:
  backend_uploads:
    driver: local
  pg_data:
    driver: local

networks:
  cslibrary-net:
    driver: bridge
