name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare .env for CI
        run: |
          cat > .env.ci <<'EOF'
          DATABASE_URL=postgresql+psycopg://csuser:password@postgres:5432/cslibrary
          ENVIRONMENT=production
          HOST=0.0.0.0
          PORT=8000
          POSTGRES_DB=cslibrary
          POSTGRES_USER=csuser
          POSTGRES_PASSWORD=password
          EOF

      - name: Start database
        run: docker compose --env-file .env.ci up -d postgres

      - name: Build backend
        run: docker compose --env-file .env.ci build backend

      - name: Run migrations
        run: docker compose --env-file .env.ci run --rm backend alembic upgrade head

      - name: Run tests
        run: docker compose --env-file .env.ci run --rm backend pytest -q

      - name: Tear down
        if: always()
        run: docker compose --env-file .env.ci down -v
