name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare .env for CI
        run: |
          cat > .env.ci <<'EOF'
          DATABASE_URL=postgresql+psycopg2://csuser:password@postgres:5432/cslibrary
          ENVIRONMENT=production
          HOST=0.0.0.0
          PORT=8000
          POSTGRES_DB=cslibrary
          POSTGRES_USER=csuser
          POSTGRES_PASSWORD=password
          BACKEND_DOCKERFILE=Dockerfile
          FRONTEND_DOCKERFILE=Dockerfile.prod
          BACKEND_PORT=8000
          FRONTEND_PORT=80
          POSTGRES_PORT=5432
          EOF

      - name: Compose config check
        run: docker compose --env-file .env.ci config > /dev/null

      - name: Build backend
        run: docker compose --env-file .env.ci build backend

      - name: Verify Python and deps
        run: |
          docker compose --env-file .env.ci run --rm backend python -c "import sys; print(sys.version)"
          docker compose --env-file .env.ci run --rm backend python -c "import psycopg2, sqlalchemy, alembic, uvicorn, gunicorn, bcrypt; from passlib.hash import bcrypt as _bcrypt; print('deps ok')"
          docker compose --env-file .env.ci run --rm backend python -m pip check

      - name: Start database
        run: docker compose --env-file .env.ci up -d postgres

      - name: Run migrations
        run: docker compose --env-file .env.ci run --rm backend alembic upgrade head

      - name: Start backend
        run: docker compose --env-file .env.ci up -d backend

      - name: Pre-check diagnostics
        run: |
          docker compose --env-file .env.ci ps
          docker compose --env-file .env.ci logs --no-color --tail=200 backend || true

      - name: Connectivity check (wait up to 30s)
        run: |
          docker compose --env-file .env.ci exec -T backend sh -lc '
            i=0
            until curl -fsS -m 5 http://localhost:8000/healthz; do
              i=$((i+1))
              if [ $i -ge 15 ]; then
                echo "Backend not ready after ~30s"
                exit 1
              fi
              echo "Waiting for backend... ($i/15)"
              sleep 2
            done
          '

      - name: Post-check diagnostics (on failure)
        if: failure()
        run: |
          docker compose --env-file .env.ci ps
          docker compose --env-file .env.ci logs --no-color --tail=300 backend || true
          docker compose --env-file .env.ci exec -T backend sh -lc "ps -ef | grep -E 'gunicorn|uvicorn' | grep -v grep || true"
          docker compose --env-file .env.ci exec -T backend sh -lc "command -v ss >/dev/null 2>&1 && ss -ltnp || (command -v netstat >/dev/null 2>&1 && netstat -ltnp) || true"

      - name: Run tests
        run: docker compose --env-file .env.ci run --rm backend pytest -q

      - name: Build frontend
        run: |
          docker build -f frontend/Dockerfile.prod --build-arg VITE_API_BASE=/api -t library-frontend ./frontend

      - name: Frontend config check
        run: node scripts/check-frontend-config.js

      - name: Start frontend
        run: docker compose --env-file .env.ci up -d --no-build frontend

      - name: Prepare test image
        run: docker compose --env-file .env.ci cp frontend/public/placeholder.jpg backend:/app/uploads/test.jpeg

      - name: Frontend integration check (wait up to 60s)
        run: |
          docker compose --env-file .env.ci exec -T frontend sh -lc '
            i=0
            while [ $i -lt 30 ]; do
              code=$(curl -fsS -o /dev/null -w "%{http_code}" http://localhost/ || true)
              if [ "$code" = "200" ] && [ -f /usr/share/nginx/html/index.html ]; then
                echo "[OK] Frontend index ready (200)"
                exit 0
              fi
              echo "Waiting for frontend... ($((i+1))/30) code=${code:-N/A}"
              i=$((i+1))
              sleep 2
            done
            echo "Frontend not ready after ~60s"
            echo "--- nginx -T (head) ---"; nginx -T 2>&1 | sed -n "1,200p" || true
            echo "--- html dir ---"; ls -lah /usr/share/nginx/html/ || true
            echo "--- index.html head ---"; [ -f /usr/share/nginx/html/index.html ] && head -n 20 /usr/share/nginx/html/index.html || true
            echo "--- backend dns ---"; getent hosts backend || true
            exit 1
          '

      - name: Frontend API proxy check (wait up to 60s)
        run: |
          docker compose --env-file .env.ci exec -T frontend sh -lc '
            i=0
            while [ $i -lt 30 ]; do
              code=$(curl -fsS -o /dev/null -w "%{http_code}" http://localhost/api/healthz || true)
              if [ "$code" = "200" ]; then
                echo "[OK] /api proxy works (200)"
                exit 0
              fi
              echo "Waiting for /api proxy... ($((i+1))/30) code=${code:-N/A}"
              i=$((i+1))
              sleep 2
            done
            echo "/api proxy not ready after ~60s"; exit 1
          '

      - name: Tear down
        if: always()
        run: docker compose --env-file .env.ci down -v
